### ISSUE TITLE
Can't boot with enabled service

### ISSUE THREAD

**Issue by KhazAkar** [openSUSE/SUSEPrime#13] opened 2019-03-25 13:13 UTC
Hello! I have problem with my openSUSE Tumbleweed on Dell Precision 5510 with Quadro M1000M. After installing drivers from repository, installing suse-prime, enabling service, setting nvidia using prime-select nvidia, after reboot systemd waits endlessly, so I cannot boot my machine. When trying to use logout-login method, I need to logout twice, one with writing my credencials, then second - automatically login me to the desktop.

**Comment by simopil** [comment] 2019-03-25 13:19
What display-manager are you using? Have you nvidia proprietary driver? Post your suse-prime log

**Comment by sndirsch** [comment] 2019-03-25 13:24
I need to admit, that the last version of suse-prime still working for me, was 0.5, i.e. before all the changes for systemd came in ...

**Comment by simopil** [comment] 2019-03-25 13:39
Remember if you do switch command then reboot, script does ANYTHING, you have to logout first, or use "prime-select next-boot nvidia" if you want to reboot

**Comment by bubbleguuum** [comment] 2019-03-25 15:39
Absolutely zero problem here. OK that does not help much...

**Comment by NickLion** [comment] 2019-03-25 17:21
I also have no problem, but there are at least 2 people in opensuse matrix tech-support room with this problem.

**Comment by KhazAkar** [comment] 2019-03-25 18:11
@simopil I'm using MATE. I have nvidia blob drivers.

**Comment by simopil** [comment] 2019-03-25 18:15
Mate with mdm as display manager? With unsupported DMs, script tells you.

**Comment by KhazAkar** [comment] 2019-03-25 18:19
About suse-prime log I have that after failed booting with service enabled - 
![JPEG_20190325_160405](https://user-images.githubusercontent.com/12693890/54943779-4f5d8980-4f32-11e9-9319-ca05a37b3db1.jpg)
What's more interesting, when using nVidia GPU I cannot enter nvidia-settings, from terminal I'm flooded with libva info messages, like that:
![JPEG_20190325_151145](https://user-images.githubusercontent.com/12693890/54943944-b11df380-4f32-11e9-834c-051a6db3d93e.jpg)
![JPEG_20190325_151248](https://user-images.githubusercontent.com/12693890/54943941-ae230300-4f32-11e9-81c5-44c3ec6bfbf1.jpg)
And I have that when trying to boot with service enabled: 
![JPEG_20190325_155955](https://user-images.githubusercontent.com/12693890/54944009-dc084780-4f32-11e9-843b-e45ba3cee274.jpg)
I'm so sorry for poor quality of images, but I was not able to capture text from PC, when internet connection just died when trying to boot - WiFi not ready etc.

**Comment by KhazAkar** [comment] 2019-03-25 18:20
@simopil no, MATE with LightDM.

**Comment by KhazAkar** [comment] 2019-03-25 18:22
And scripts tells nothing, which I can assume LightDM is supported.

**Comment by simopil** [comment] 2019-03-25 18:33
Try this:
sudo echo "nvidia" > /etc/prime/current_type
The reboot

**Comment by KhazAkar** [comment] 2019-03-25 18:51
Can't boot, same waiting screen.

**Comment by simopil** [comment] 2019-03-25 19:20
Can you post content of all files in /etc/prime directory and result of prime-select service status ?

**Comment by simopil** [comment] 2019-03-27 10:57
I talked about issue with guys from matrix tech-support, works with files and service manually-copied, NOT work (for me too) with RPM package, seems there's issue with systemd services

**Comment by sndirsch** [comment] 2019-03-27 11:36
> I talked about issue with guys from matrix tech-support, works with files and service manually-copied, NOT work (for me too) with RPM package, seems there's issue with systemd services

Which RPM package? The suse-prime one of Leap 15.1/TW with suse-prime 0.5 or obs://X11:XOrg/suse-prime (version 0.6.6)? I accepted some package changes recently in X11:XOrg

# osc diff -r23:24
+- Split power support into separate package suse-prime-bbswitch
+  which don't need manual work

**Comment by simopil** [comment] 2019-03-27 11:44
0.6.6 one, I don't know how packages now works. Are both necessary?(suse-prime and suse-prime-bbswitch)

**Comment by sndirsch** [comment] 2019-03-27 13:17
> 0.6.6 one, I don't know how packages now works. Are both necessary?(suse-prime and suse-prime-bbswitch)
suse-prime and suse-prime-bbswitch conflict now

**Comment by simopil** [comment] 2019-03-27 17:51
Finally issue is caused by plymouth animation that hangs at boot when prime-boot-selector service is enabled. Disabling plymouth with "plymouth.enable=0" in kernel parameters resolves the issue

**Comment by bubbleguuum** [comment] 2019-03-27 18:11
Urgh. That would explain why it always worked for me: I always had Plymouth disabled (wall of text FTW!).

**Comment by simopil** [comment] 2019-03-27 19:04
Same for me, indeed finding bug was quite hard

**Comment by simopil** [comment] 2019-03-28 09:13
I've done some tests, plymouth works well with prime if "prime-boot-selector.service" parameter is present in "After=" of "plymouth-quit-wait.service", but if I put plymouth-quit-wait.service in "Before=" of prime-boot-selector.service it doesn't work

**Comment by sndirsch** [comment] 2019-03-28 09:43
<pre>
> I've done some tests, plymouth works well with prime if "prime-boot-selector.service" parameter is
> present in "After=" of "plymouth-quit-wait.service", but if I put plymouth-quit-wait.service in "Before=" 
> of prime-boot-selector.service it doesn't work
Welcome to the race condition hello of plymouth. :-(
</pre>

**Comment by simopil** [comment] 2019-03-28 11:58
It can be set as disabled during rpm setup?

**Comment by sndirsch** [comment] 2019-03-28 14:26
<pre>
> It can be set as disabled during rpm setup?
plymouth? Sure, e.g.

cat >> %{buildroot}/etc/dracut.conf.d/50-nvidia-$flavor.conf << EOF
omit_dracutmodules+="plymouth"
EOF
Of course afterwards dracut needs to be running ...
</pre>

**Comment by simopil** [comment] 2019-03-29 10:52
It's sufficient adding plymouth.enable=0 in kernel parameters, please report to package mantainer 'cause people that install suse-prime and have it enabled have an unbootable system

**Comment by simopil** [comment] 2019-03-29 14:36
So, it's strange but a reinstallation of plymouth fixed bug for me

**Comment by bubbleguuum** [comment] 2019-03-29 16:39
I think I have a simple fix for the plymouth issue.
Basically, `prime-boot-selector.service` depending on `display-manager.service` is incompatible with `plymouth-quit-wait.service`. The good news is that we do not have to depend on `display-manager.service` and can run `prime-boot-selector.service` a tad much earlier in the boot process without any side effect (that I can think of). It doesn't even need to run after multi-user.target.
This modified `prime-boot-selector.service` works with and without plymouth enabled:

```
[Unit]
Description=Prime Select Service (Boot Selector)

[Service]
Type=oneshot
ExecStart=prime-select prime_booting

[Install]
WantedBy=multi-user.target
```

@simopil (and others) can you test this `prime-boot-selector.service` (replace exiting file in /usr/lib/systemd/system) and report if it works for you ? If it does I will submit a PR.

**Comment by simopil** [comment] 2019-03-29 21:29
Tomorrow i will try. So I remember that without "Before=display-manager.service" didn't work for you (https://github.com/openSUSE/SUSEPrime/pull/3#issuecomment-457649921)

**Comment by simopil** [comment] 2019-03-30 09:33
your .service working for me in new single service, I'm waiting feedback from openSUSE Tech channell in Matrix

**Comment by bubbleguuum** [comment] 2019-03-30 10:35
I didn't try with your latest PR from yesterday, but with the previous version the nvidia card was awlays off when required (intel configurations) in my testing. In the case of the nvidia config, we really need to load the nvidia modules (thus run the service) as early as possible at boot, in the case the nvidia card is the only one available (set in BIOS by user). Otherwise, the machine boots with a black screen until the module are loaded.

**Comment by simopil** [comment] 2019-03-30 10:57
maybe by removing them from modprobe blacklist and unload if intel selected. I'm thinking about command like "prime-select early-load driver" that choose non-blacklisted module at boot.

**Comment by bubbleguuum** [comment] 2019-03-30 11:23
It's far easier to load the nvidia modules when needed (current situation) rather than the opposite. 
Please don't make it even more complicated. Not much is needed at this point: we just need the Plymouth problem fixed and the updated service I posted should fix it.

**Comment by simopil** [comment] 2019-03-30 11:34
I want to make it easier, this is the reason for my pull request with one only service

**Comment by simopil** [comment] 2019-04-02 13:58
@bubbleguuum have you tried new version and plymouth and/or nvidia disabled by bios without "After=multi-user.target" but with "Before=display-manager.service" one?

**Comment by bubbleguuum** [comment] 2019-04-02 14:20
Not yet but I will try it tonight, testing different combinations.

**Comment by bubbleguuum** [comment] 2019-04-02 17:09
@simopil 

I have tested current master with your latest changes.
I works without Plymouth. With Plymouth, same problem: plymouth remain stuck at boot for the reason mentionned in my previous post.

So I tried removing dependencies in prime-select.service, in the Unit section:

```
[Unit]
Description=SUSEPrime systemd service

[Service]
Type=oneshot
ExecStart=prime-select systemd_call

[Install]
WantedBy=multi-user.target

```

With this, it works with (and without) Plymouth BUT... disabling the nvidia card with bbswitch when not needed (eg nvidia -> intel) does not work anymore. That is, starting in a situtation with the nvidia driver active and doing the sequence below results in NVIDIA card ON:

- prime-select intel
- <logout>
- <login>
- prime-select get-current
Driver configured: intel
[bbswitch] NVIDIA card is ON

I'm not sure but this could be due to prime-select.sh doing `systemctl isolate multi-user.target'.

So the last hurdle is to have the prime-select.service play nice with Plymouth. Either find a combination of dependencies that are compatible with Plymouth, or using the prime-select.service and fixing the failure to unload nvidia modules resulting in a the inability to turn off the card with bbswitch.

**Comment by simopil** [comment] 2019-04-02 17:13
Try to leave only "Before=display-manager.service", plymouth works in my system with this combination:

[Unit]
Description=SUSEPrime systemd service
Before=display-manager.service

[Service]
Type=oneshot
ExecStart=prime-select systemd_call

[Install]
WantedBy=multi-user.target

**Comment by bubbleguuum** [comment] 2019-04-02 17:20
Confirming that is works with this ! nvidia module is properly switched off and Plymouth works.
I suggest you submit a PR with this change.

**Comment by bubbleguuum** [comment] 2019-04-02 17:22
Also README.md needs to be updated (you mentioned it in latest patch but the file was not in the PR)

**Comment by simopil** [comment] 2019-04-02 17:24
It's strange (readme file), I'll do this

**Comment by sndirsch** [comment] 2019-10-03 12:05
Haven't seen such an issue with SUSEPrime 0.7. Let's close it as fixed. Otherwise please open a new issue.

**Closed by sndirsch** 2019-10-03 12:05 UTC
